FROM debian:bookworm AS builder
ARG XMAKE_VERSION="v2.9.7"
# 定义代理环境变量
ARG HTTP_PROXY
ARG NO_PROXY=localhost,127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,.cn

# 设置环境变量
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTP_PROXY}
ENV NO_PROXY=${NO_PROXY}
ENV XMAKE_ROOT=y

RUN rm -rf /etc/apt/sources.list.d/debian.sources &&\
    printf 'deb http://mirrors.tuna.tsinghua.edu.cn/debian/ sid main contrib non-free non-free-firmware\ndeb http://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware\n' > /etc/apt/sources.list

#----##可修改## 安装基础构建环境----
RUN DEBIAN_FRONTEND=noninteractive apt update &&\
    apt install -y ca-certificates build-essential python3 python3-pip iputils-ping curl wget unzip libffi-dev cmake ninja-build &&\
    apt install -y gcc-13 g++-13 &&\
    apt install -y bash

SHELL ["/bin/bash","-c"]
#----##不要动## 安装xmake----
RUN curl -fsSL https://xmake.io/shget.text | bash -s ${XMAKE_VERSION}
#----##不要动## 安装依赖----
RUN apt install -y libopencv-dev libssl-dev openssl python3.13-dev
#----##不要动## 复制基础xmake文件，用于构建第三方库----
COPY ./app/xmake.lua /src/app/xmake.lua
COPY ./app/source/xmake.lua /src/app/source/xmake.lua
COPY ./app/source/third /src/app/source/third/
COPY ./scripts /src/scripts/
COPY ./xmake /src/xmake/
COPY ./xmake.lua /src/xmake.lua
#----##可修改## 配置项目，构建第三方库，可以修改xmake相关命令----
RUN cd /src&&source ~/.xmake/profile&&\
    xmake f -c -p linux --toolchain=gcc-13 -a x86_64 -k binary -m release -o build/release-linux -vy
#----##不要动## 复制项目资产、配置、源码----
COPY ./app/assets /src/app/assets/
COPY ./app/binaries /src/app/binaries/
COPY ./app/config /src/app/config/
COPY ./app/source/programs /src/app/source/programs/
COPY ./app/source/runtime /src/app/source/runtime/
#----##请修改## 构建项目----
RUN cd /src&&source ~/.xmake/profile &&\
    xmake build -v demo

#----##请修改## 安装项目，后处理----
RUN mkdir /app &&\
    cp -r /src/build/release-linux/linux/x86_64/release/* /app &&\
    cd /app && ln -s libonnxruntime.so libonnxruntime.so.1
#----##请修改## 二阶段----
FROM debian:bookworm
COPY --from=builder /app /app
EXPOSE 11451
WORKDIR /app
ENTRYPOINT ["demo"]